/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {StyleSheet, Text, View, TouchableOpacity} from 'react-native';
import WXSdk, {WXScene} from '@byron-react-native/wechat';

const kTextMessage =
  '人文的东西并不是体现在你看得到的方面，它更多的体现在你看不到的那些方面，它会影响每一个功能，这才是最本质的。但是，对这点可能很多人没有思考过，以为人文的东西就是我们搞一个很小清新的图片什么的。”综合来看，人文的东西其实是贯穿整个产品的脉络，或者说是它的灵魂所在。';

const kImageTagName = 'WECHAT_TAG_JUMP_APP';
const kMessageExt = '这是第三方带的测试字段';
const kMessageAction = '<action>dotalist</action>';

const kLinkURL = 'http://tech.qq.com/zt2012/tmtdecode/252.htm';
const kLinkTagName = 'WECHAT_TAG_JUMP_SHOWRANK';
const kLinkTitle = '专访张小龙：产品之上的世界观';
const kLinkDescription =
  '微信的平台化发展方向是否真的会让这个原本简洁的产品变得臃肿？在国际化发展方向上，微信面临的问题真的是文化差异壁垒吗？腾讯高级副总裁、微信产品负责人张小龙给出了自己的回复。';

const kMusicURL =
  'http://y.qq.com/i/song.html#p=7B22736F6E675F4E616D65223A22E4B880E697A0E68980E69C89222C22736F6E675F5761704C69766555524C223A22687474703A2F2F74736D7573696334382E74632E71712E636F6D2F586B30305156342F4141414130414141414E5430577532394D7A59344D7A63774D4C6735586A4C517747335A50676F47443864704151526643473444442F4E653765776B617A733D2F31303130333334372E6D34613F7569643D3233343734363930373526616D703B63743D3026616D703B636869643D30222C22736F6E675F5769666955524C223A22687474703A2F2F73747265616D31342E71716D757369632E71712E636F6D2F33303130333334372E6D7033222C226E657454797065223A2277696669222C22736F6E675F416C62756D223A22E4B880E697A0E68980E69C89222C22736F6E675F4944223A3130333334372C22736F6E675F54797065223A312C22736F6E675F53696E676572223A22E5B494E581A5222C22736F6E675F576170446F776E4C6F616455524C223A22687474703A2F2F74736D757369633132382E74632E71712E636F6D2F586C464E4D313574414141416A41414141477A4C36445039536A457A525467304E7A38774E446E752B6473483833344843756B5041576B6D48316C4A434E626F4D34394E4E7A754450444A647A7A45304F513D3D2F33303130333334372E6D70333F7569643D3233343734363930373526616D703B63743D3026616D703B636869643D3026616D703B73747265616D5F706F733D35227D';
const kMusicDataURL = 'http://stream20.qqmusic.qq.com/32464723.mp3';
const kMusicTitle = '一无所有';
const kMusicDescription = '崔健';

const kVideoURL = 'http://v.youku.com/v_show/id_XNTUxNDY1NDY4.html';
const kVideoTitle = '乔布斯访谈';
const kVideoDescription = '饿着肚皮，傻逼着。';

const kAPPContentTitle = 'App消息';
const kAPPContentDescription = '这种消息只有App自己才能理解，由App指定打开方式';
const kAppContentExInfo = '<xml>extend info</xml>';
const kAppContnetExURL = 'http://weixin.qq.com';
const kAppMessageExt = '这是第三方带的测试字段';
const kAppMessageAction = '<action>dotaliTest</action>';

const kAuthScope =
  'snsapi_message,snsapi_userinfo,snsapi_friend,snsapi_contact';
const kAuthOpenID = '0c806938e2413ce73eef92cc3';
const kAuthState = 'xxx';

const kFileTitle = 'iphone4.pdf';
const kFileDescription = 'Pro CoreData';
const kFileExtension = 'pdf';
const kFileName = 'iphone4';

const kProfileExtMsg =
  'http://we.qq.com/d/AQCIc9a3EqRfb19z8WnLB6iFNCxX5bO2S3lHwMQL';
const kBizWebviewExtMsg = 'KOoCKdavezBjdj2wJZsq67N2j_g3XEQ5JP_pkLhBYS4';

const kMiniProgramTitle = '小程序title';
const kMiniProgramDesc = '小程序Desc';

const filePath =
  'https://app.yuliaoapp.com/static/media/pic3.5316b9cfe295a6b85b34.png';

export default class App extends Component {
  state = {
    status: 'starting',
    message: '--',
  };

  registerApp = async () => {
    const bool = await WXSdk.registerApp(
      'wxd930ea5d5a258f4f',
      'https://help.wechat.com/sdksample/',
    );
    console.log(' >> registerApp:', bool);
    if (!bool) {
      this.setState({
        status: 'failed to activate',
      });
      return;
    }
    const message = await WXSdk.getApiVersion();
    this.setState({message});
    WXSdk.getWXAppInstallUrl().then(res => {
      console.log(' >> WXAppInstallUrl:', res);
    });
    WXSdk.isWXAppInstalled().then(res => {
      console.log(' >> isWXAppInstalled:', res);
    });
    WXSdk.isWXAppSupportApi().then(res => {
      console.log(' >> isWXAppSupportApi:', res);
    });
    WXSdk.subscription(
      '1000',
      '7YuTL__ilzyZB9DXcDt2mHx-CAS_E7KtsQkhIGVhhRM',
      '',
      data => {
        console.log(' >> subscription:', data);
      },
    );
  };

  sendTextContent = () => {
    WXSdk.sendText(kTextMessage, WXScene.WXSceneSession).then(res => {
      console.log(' >> sendText:', res);
    });
  };

  sendImageContent = () => {
    WXSdk.sendImage({
      filePath: filePath,
      tagName: kImageTagName,
      messageExt: kMessageExt,
      action: kMessageAction,
      thumbPath: filePath,
      scene: WXScene.WXSceneSession,
    }).then(res => {
      console.log(' >> sendImage:', res);
    });
  };

  sendLinkContent = () => {
    WXSdk.sendLinkURL({
      url: kLinkURL,
      tagName: kLinkTagName,
      title: kLinkTitle,
      description: kLinkDescription,
      thumbPath: filePath,
      scene: WXScene.WXSceneSession,
    }).then(res => {
      console.log(' >> sendLinkURL:', res);
    });
  };

  sendMusicContent = () => {
    WXSdk.sendMusicURL({
      url: kMusicURL,
      dataURL: kMusicDataURL,
      title: kMusicTitle,
      description: kMusicDescription,
      thumbPath: filePath,
      scene: WXScene.WXSceneSession,
    }).then(res => {
      console.log(' >> sendMusicURL:', res);
    });
  };

  sendVideoContent = () => {
    WXSdk.sendVideoURL({
      url: kVideoURL,
      title: kVideoTitle,
      description: kVideoDescription,
      thumbPath: filePath,
      scene: WXScene.WXSceneSession,
    }).then(res => {
      console.log(' >> sendVideoURL:', res);
    });
  };

  sendAppContent = () => {
    WXSdk.sendAppData({
      info: kAppContentExInfo,
      url: kAppContnetExURL,
      title: kAPPContentTitle,
      description: kAPPContentDescription,
      messageExt: kAppMessageExt,
      action: kAppMessageAction,
      thumbPath: filePath,
      scene: WXScene.WXSceneSession,
    }).then(res => {
      console.log(' >> sendAppData:', res);
    });
  };

  sendEmotionContent = () => {
    WXSdk.sendEmotionData(
      filePath,
      filePath,
      WXScene.WXSceneSession,
    ).then(res => {
      console.log(' >> sendEmotionData:', res);
    });
  };

  sendAuthRequest = () => {
    WXSdk.sendAuth(kAuthScope, kAuthState, kAuthOpenID).then(res => {
      console.log(' >> sendAuth:', res);
    });
  };

  sendFileContent = () => {
    WXSdk.sendFileData({
      filePath:
        'https://www.lilnong.top/static/pdf/B-4-RxJS%E5%9C%A8React%E4%B8%AD%E7%9A%84%E5%BA%94%E7%94%A8-%E9%BE%99%E9%80%B8%E6%A5%A0_.pdf',
      extension: 'pdf',
      title: kFileTitle,
      description: kFileDescription,
      thumbPath: filePath,
      scene: WXScene.WXSceneSession,
    }).then(res => {
      console.log(' >> sendFileData:', res);
    });
  };

  addCardToWXCardPackage = () => {
    WXSdk.addCardsToCardPackage(
      'wxf8b4f85f3a794e77',
      ['pDF3iY9tv9zCGCj4jTXFOo1DxHdo'],
      [
        JSON.stringify({
          code: '',
          openid: '',
          timestamp: '1418301401',
          signature: 'ad9cf9463610bc8752c95084716581d52cd33aa0',
        }),
      ],
    ).then(res => {
      console.log(' >> addCardsToCardPackage:', res);
    });
  };

  chooseCard = () => {
    WXSdk.chooseCard({
      appid: 'wxf8b4f85f3a794e77',
      cardSign: '6caa49f4a5af3d64ac247e1f563e5b5eb94619ad',
      nonceStr: 'k0hGdSXKZEj3Min5',
      signType: 'SHA1',
      timestamp: 1437997723,
    }).then(res => {
      console.log(' >> chooseCard:', res);
    });
  };

  // chooseInvoiceTicket = () => {
  //   WXSdk.chooseInvoice({

  //   })
  // }

  sendAppBrand = () => {
    WXSdk.sendMiniProgramWebpageUrl({
      webpageUrl: 'https://www.baidu.com',
      userName: 'gh_d43f693ca31f',
      path: '',
      title: kMiniProgramTitle,
      description: kMiniProgramDesc,
      thumbImagePath: filePath,
      hdImagePath: filePath,
      withShareTicket: true,
      scene: WXScene.WXSceneSession,
    }).then(res => {
      console.log(' >> sendMiniProgramWebpageUrl:', res);
    });
  };

  launchMiniProgram = () => {
    WXSdk.launchMiniProgramWithUserName('gh_d43f693ca31f@app', '').then(res => {
      console.log(' >> launchMiniProgramWithUserName:', res);
    });
  };

  componentDidMount() {
    this.registerApp();
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆Wechat example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <TouchableOpacity style={styles.button} onPress={this.sendTextContent}>
          <Text style={styles.text}>发送Text消息给微信</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.button} onPress={this.sendImageContent}>
          <Text style={styles.text}>发送Photo消息给微信</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.button} onPress={this.sendLinkContent}>
          <Text style={styles.text}>发送Link消息给微信</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.button} onPress={this.sendMusicContent}>
          <Text style={styles.text}>发送Music消息给微</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.button} onPress={this.sendVideoContent}>
          <Text style={styles.text}>发送Video消息给微信</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.button} onPress={this.sendAppContent}>
          <Text style={styles.text}>发送App消息给微信</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.button}
          onPress={this.sendEmotionContent}>
          <Text style={styles.text}>发送表情给微信</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.button} onPress={this.sendAuthRequest}>
          <Text style={styles.text}>微信授权登录</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.button} onPress={this.sendFileContent}>
          <Text style={styles.text}>发送文件消息给微信</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.button}
          onPress={this.addCardToWXCardPackage}>
          <Text style={styles.text}>添加卡券至卡包</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.button} onPress={this.chooseCard}>
          <Text style={styles.text}>选择卡券</Text>
        </TouchableOpacity>
        {/* <TouchableOpacity style={styles.button} onPress={this.chooseInvoiceTicket}>
          <Text style={styles.text}>选择发票</Text>
        </TouchableOpacity> */}
        <TouchableOpacity style={styles.button} onPress={this.sendAppBrand}>
          <Text style={styles.text}>小程序分享</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.button}
          onPress={this.launchMiniProgram}>
          <Text style={styles.text}>拉起小程序</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  button: {
    width: 200,
    height: 30,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2da44e',
    marginVertical: 3,
  },
  text: {
    fontSize: 14,
    color: '#fff',
  },
});
